name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Create kubeconfig file
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f manifests/
